apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  host: {{ .Values.appName }}.{{ .Values.namespace }}.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
