apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.appName}}
  namespace: {{ .Values.namespace}}
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  servers:
    {{- range .Values.hosts }}
    - hosts:
      - {{ . }}
      port:
        name: http
        number: {{ $.Values.gateway.port }}
        protocol: HTTP
    {{- end }}