# Default values for ping-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: ghcr.io/ninbes/pong
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: 
  name: ghcr-secret

service:
  type: ClusterIP
  port: 80

appName: pong
namespace: app-service
hosts: 
    - pong.app.kind.org
gateway:
    port: 80

virtualService:
    port: 80