# Default values for dateresponder-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/ninbes/dateresponder
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
appName: dateresponder
namespace: app-service
hosts: 
    - dateresponder.app.kind.org
gateway:
    port: 80

virtualService:
    port: 80

imagePullSecrets: 
  name: ghcr-secret

service:
  type: ClusterIP
  port: 80

